#!/bin/sh

# PROVIDE: glass_hbbs
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# glass_hbbs_enable (bool):            Set to NO by default.
#               Set it to YES to enable glass_hbbs.
# glass_hbbs_args (string):            Set extra arguments to pass to glass_hbbs
#               Default is "-r ${glass_hbbs_ip} -k _".
# glass_hbbs_user (string):            Set user that glass_hbbs will run under
#               Default is "root".
# glass_hbbs_group (string):           Set group that glass_hbbs will run under
#               Default is "wheel".

. /etc/rc.subr

name=glass_hbbs
desc="Qompass Glass ID/Rendezvous Server"
rcvar=glass_hbbs_enable

load_rc_config $name

: ${glass_hbbs_enable:=NO}
: ${glass_hbbs_ip:=127.0.0.1}
: ${glass_hbbs_args="-r ${glass_hbbs_ip} -k _"}
: ${glass_hbbs_user:=glass}
: ${glass_hbbs_group:=glass}

pidfile=/var/run/glass_hbbs.pid
command=/usr/sbin/daemon
procname=/usr/local/sbin/hbbs
glass_hbbs_chdir=/var/db/glass-server
command_args="-p ${pidfile} -o /var/log/glass-hbbs.log ${procname} ${glass_hbbs_args}"
## If you want the daemon to do its log over syslog, comment out the above line and remove the comment from the below replacement
#command_args="-p ${pidfile} -T ${name} ${procname} ${glass_hbbs_args}"

start_precmd=glass_hbbs_startprecmd

glass_hbbs_startprecmd()
{
    if [ -e ${pidfile} ]; then
        chown ${glass_hbbs_user}:${glass_hbbs_group} ${pidfile};
    else
        install -o ${glass_hbbs_user} -g ${glass_hbbs_group} /dev/null ${pidfile};
    fi
    if [ -e ${glass_hbbs_chdir} ]; then
        chown -R ${glass_hbbs_user}:${glass_hbbs_group} ${glass_hbbs_chdir};
        chmod -R 770 ${glass_hbbs_chdir};
    else
        mkdir -m 770 ${glass_hbbs_chdir};
        chown ${glass_hbbs_user}:${glass_hbbs_group} ${glass_hbbs_chdir};
    fi
    if [ -e /var/log/glass-hbbs.log ]; then
        chown -R ${glass_hbbs_user}:${glass_hbbs_group} /var/log/glass-hbbs.log;
        chmod 660 /var/log/glass-hbbs.log;
    else
        install -o ${glass_hbbs_user} -g ${glass_hbbs_group} /dev/null /var/log/glass-hbbs.log;
        chmod 660 /var/log/glass-hbbs.log;
    fi
}

run_rc_command "$1"
